<<<<<<< HEAD
SELECT * FROM PLDA.CPDECLARATION 

SELECT * FROM PLDA.CPDECLARATION WHERE PRINCIPAL = 'CASAINTERN'

SELECT * FROM PLDA.CPDECLARTARIFCNT  

SELECT PLDA.CPDECLHISTORY.STATUSDECLARATION,PLDA.CPDECLHISTORY.HISTORYDATE, PLDA.CPDECLHISTORY.HISTORYTIME, PLDA.CPDECLARATION.PRINCIPAL, PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
  AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'REL_TRA'
  AND PLDA.CPDECLARATION.PRINCIPAL <> 'MARKEN'
  AND PLDA.CPDECLHISTORY.HISTORYTIME >= '180000'
FETCH FIRST 2 ROWS ONLY


SELECT 
    PLDA.CPDECLHISTORY.STATUSDECLARATION,
    PLDA.CPDECLHISTORY.HISTORYDATE,
    PLDA.CPDECLHISTORY.HISTORYTIME,
    PLDA.CPDECLARATION.PRINCIPAL,
    PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM 
    PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE 
    PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
    AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'REL_TRA'
    AND PLDA.CPDECLARATION.PRINCIPAL = 'CASAINTERN'
FETCH FIRST 10 ROWS ONLY





SELECT 
    PLDA.CPDECLHISTORY.STATUSDECLARATION,
    PLDA.CPDECLHISTORY.HISTORYDATE,
    PLDA.CPDECLHISTORY.HISTORYTIME,
    PLDA.CPDECLARATION.PRINCIPAL,
    PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM 
    PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE 
    PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
    AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'CREATE'
    AND TO_DATE(PLDA.CPDECLHISTORY.HISTORYDATE || PLDA.CPDECLHISTORY.HISTORYTIME, 'YYYYMMDDHH24MISS') 
        BETWEEN TRUNC(SYSDATE, 'HH24') AND TRUNC(SYSDATE + 1/24, 'HH24')


/*LUC instructions*/
SELECT 
    d.DATEOFACCEPTANCE,
    d.MRN,
    c.IDENTIFICATIONNUMBER
FROM 
    EUCDM.EUCDECLARATION d
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID
WHERE 
    d.DATEOFACCEPTANCE = TO_DATE('16-01-2024', 'DD-MM-YYYY')
    AND d.MRN IS NOT NULL
    AND c.IDENTIFICATIONNUMBER IS NOT NULL

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.ILSPRINCIPAL,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD') as DATEOFACCEPTANCE, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE, 
    d.MESSAGESTATUS,
    d.MRN,
    d.ACTIVECOMPANY,   


SELECT 
    d.DECLARATIONID,
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE, 'HH24') = TRUNC(SYSDATE, 'HH24')
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID
-------------------------------------------------------------------------------------
SELECT 
    d.DECLARATIONID,
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND TRUNC(d.DATEOFACCEPTANCE, 'HH24') = TRUNC(SYSDATE, 'HH24')
    AND c.IDENTIFICATIONNUMBER IS NOT NULL
GROUP BY 
    d.DECLARATIONID







/*Request to the functiosn*/
https://functionapp-python-pdf.azurewebsites.net/api/DailyContainerCheck?code=WojhELuZgjmzAl8_R0RqQ5BKoUDS3fTj49eUt1DK2I4MAzFuEPJ7SQ%3D%3D
{
  "data": @{body('Execute_a_Oracle_query')?['resultsets']}
}





SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.ISSUEDATETIME,
    TO_CHAR(d.ISSUEDATETIME, 'YYYY-MM-DD HH24:MI:SS') as ISSUEDATETIME, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    d.MESSAGESTATUS = 'CREATE'
    AND d.ISSUEDATETIME BETWEEN SYSDATE - INTERVAL '15' MINUTE AND SYSDATE
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE,
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.ISSUEDATETIME,
    d.MRN


---------------------------------------------------------------------------

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRIM(d.MRN) IS NOT NULL
    AND d.DATEOFACCEPTANCE BETWEEN SYSDATE - INTERVAL '1' HOUR AND SYSDATE
    AND c.IDENTIFICATIONNUMBER IS NOT NULL
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE,
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.MRN
=======
SELECT * FROM PLDA.CPDECLARATION 

SELECT * FROM PLDA.CPDECLARATION WHERE PRINCIPAL = 'CASAINTERN'

SELECT * FROM PLDA.CPDECLARTARIFCNT  

SELECT PLDA.CPDECLHISTORY.STATUSDECLARATION,PLDA.CPDECLHISTORY.HISTORYDATE, PLDA.CPDECLHISTORY.HISTORYTIME, PLDA.CPDECLARATION.PRINCIPAL, PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
  AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'REL_TRA'
  AND PLDA.CPDECLARATION.PRINCIPAL <> 'MARKEN'
  AND PLDA.CPDECLHISTORY.HISTORYTIME >= '180000'
FETCH FIRST 2 ROWS ONLY


SELECT 
    PLDA.CPDECLHISTORY.STATUSDECLARATION,
    PLDA.CPDECLHISTORY.HISTORYDATE,
    PLDA.CPDECLHISTORY.HISTORYTIME,
    PLDA.CPDECLARATION.PRINCIPAL,
    PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM 
    PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE 
    PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
    AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'REL_TRA'
    AND PLDA.CPDECLARATION.PRINCIPAL = 'CASAINTERN'
FETCH FIRST 10 ROWS ONLY





SELECT 
    PLDA.CPDECLHISTORY.STATUSDECLARATION,
    PLDA.CPDECLHISTORY.HISTORYDATE,
    PLDA.CPDECLHISTORY.HISTORYTIME,
    PLDA.CPDECLARATION.PRINCIPAL,
    PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM 
    PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE 
    PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
    AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'CREATE'
    AND TO_DATE(PLDA.CPDECLHISTORY.HISTORYDATE || PLDA.CPDECLHISTORY.HISTORYTIME, 'YYYYMMDDHH24MISS') 
        BETWEEN TRUNC(SYSDATE, 'HH24') AND TRUNC(SYSDATE + 1/24, 'HH24')


/*LUC instructions*/
SELECT 
    d.DATEOFACCEPTANCE,
    d.MRN,
    c.IDENTIFICATIONNUMBER
FROM 
    EUCDM.EUCDECLARATION d
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID
WHERE 
    d.DATEOFACCEPTANCE = TO_DATE('16-01-2024', 'DD-MM-YYYY')
    AND d.MRN IS NOT NULL
    AND c.IDENTIFICATIONNUMBER IS NOT NULL

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.ILSPRINCIPAL,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD') as DATEOFACCEPTANCE, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE, 
    d.MESSAGESTATUS,
    d.MRN,
    d.ACTIVECOMPANY,   


    EUCDM.V_EUC_ALLCONTAINERS.DECLARATIONID


SELECT 
    d.DECLARATIONID,
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE, 'HH24') = TRUNC(SYSDATE, 'HH24')
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID
-------------------------------------------------------------------------------------
SELECT 
    d.DECLARATIONID,
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND TRUNC(d.DATEOFACCEPTANCE, 'HH24') = TRUNC(SYSDATE, 'HH24')
    AND c.IDENTIFICATIONNUMBER IS NOT NULL
GROUP BY 
    d.DECLARATIONID







/*Request to the functiosn*/
https://functionapp-python-pdf.azurewebsites.net/api/DailyContainerCheck?code=WojhELuZgjmzAl8_R0RqQ5BKoUDS3fTj49eUt1DK2I4MAzFuEPJ7SQ%3D%3D
{
  "data": @{body('Execute_a_Oracle_query')?['resultsets']}
}

>>>>>>> cb8cf0c73bae0e72433cdc2cff17e925e531cdde
