SELECT * FROM PLDA.CPDECLARATION 

SELECT * FROM PLDA.CPDECLARATION WHERE PRINCIPAL = 'CASAINTERN'

SELECT * FROM PLDA.CPDECLARTARIFCNT  

SELECT PLDA.CPDECLHISTORY.STATUSDECLARATION,PLDA.CPDECLHISTORY.HISTORYDATE, PLDA.CPDECLHISTORY.HISTORYTIME, PLDA.CPDECLARATION.PRINCIPAL, PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
  AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'REL_TRA'
  AND PLDA.CPDECLARATION.PRINCIPAL <> 'MARKEN'
  AND PLDA.CPDECLHISTORY.HISTORYTIME >= '180000'
FETCH FIRST 2 ROWS ONLY
-------------------------------------------------------------------------------------


























SELECT
    d.DECLARATION_ID,
    d.PRINCIPAL, 
    t.PACKAGES, 
    t.GROSSMASS, 
    t.NETMASS, 
    t.COMMODITYCODE, 
    d.COMMERCIALREFERENCE, 
    d.CONTROL_PACKAGES, 
    d.CONTROL_GROSSMASS, 
    d.CONTROL_NETMASS
FROM PLDA.CPDECLARATION d
JOIN PLDA.CPDECLARTARIF t 
    ON t.DECLARATION_ID = d.DECLARATION_ID
WHERE d.PRINCIPAL = 'CASAINTERN'
AND d.COMMERCIALREFERENCE = 'MEDU4724476'



OUTPUT.JSON


OUTPUT.GET()

INSERT (
    test.get("id"),
    test.get("name"),
)
IN TO PLDA.CPDECLARATION





SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE
FROM 
    EUCDM.EUCDECLARATION d 
WHERE 
    d.PROCEDURETYPESSW = 'H2'
    AND d.WAREHOUSEIDENTIFIER = 'U-00211-A'
    AND d.MESSAGESTATUS = 'DMSCLE'

















-------------------------------------------------------------------------------------
SELECT 
    PLDA.CPDECLHISTORY.STATUSDECLARATION,
    PLDA.CPDECLHISTORY.HISTORYDATE,
    PLDA.CPDECLHISTORY.HISTORYTIME,
    PLDA.CPDECLARATION.PRINCIPAL,
    PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM 
    PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE 
    PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
    AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'REL_TRA'
    AND PLDA.CPDECLARATION.PRINCIPAL = 'CASAINTERN'
FETCH FIRST 10 ROWS ONLY





SELECT 
    PLDA.CPDECLHISTORY.STATUSDECLARATION,
    PLDA.CPDECLHISTORY.HISTORYDATE,
    PLDA.CPDECLHISTORY.HISTORYTIME,
    PLDA.CPDECLARATION.PRINCIPAL,
    PLDA.CPDECLARATION.CUSTOMSMAINREFERENCENUMBER
FROM 
    PLDA.CPDECLHISTORY, PLDA.CPDECLARATION
WHERE 
    PLDA.CPDECLHISTORY.DECLARATION_ID = PLDA.CPDECLARATION.DECLARATION_ID
    AND PLDA.CPDECLHISTORY.STATUSDECLARATION = 'CREATE'
    AND TO_DATE(PLDA.CPDECLHISTORY.HISTORYDATE || PLDA.CPDECLHISTORY.HISTORYTIME, 'YYYYMMDDHH24MISS') 
        BETWEEN TRUNC(SYSDATE, 'HH24') AND TRUNC(SYSDATE + 1/24, 'HH24')


/*LUC instructions*/
SELECT 
    d.DATEOFACCEPTANCE,
    d.MRN,
    c.IDENTIFICATIONNUMBER
FROM 
    EUCDM.EUCDECLARATION d
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID
WHERE 
    d.DATEOFACCEPTANCE = TO_DATE('16-01-2024', 'DD-MM-YYYY')
    AND d.MRN IS NOT NULL
    AND c.IDENTIFICATIONNUMBER IS NOT NULL

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.ILSPRINCIPAL,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD') as DATEOFACCEPTANCE, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE, 
    d.MESSAGESTATUS,
    d.MRN,
    d.ACTIVECOMPANY,   


SELECT 
    d.DECLARATIONID,
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE, 'HH24') = TRUNC(SYSDATE, 'HH24')
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID
-------------------------------------------------------------------------------------
SELECT 
    d.DECLARATIONID,
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND TRUNC(d.DATEOFACCEPTANCE, 'HH24') = TRUNC(SYSDATE, 'HH24')
    AND c.IDENTIFICATIONNUMBER IS NOT NULL
GROUP BY 
    d.DECLARATIONID
-----------------------------------------------------------------------------------------
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.ISSUEDATETIME,
    TO_CHAR(d.ISSUEDATETIME, 'YYYY-MM-DD HH24:MI:SS') as ISSUEDATETIME, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    d.MESSAGESTATUS = 'CREATE'
    AND d.ISSUEDATETIME BETWEEN SYSDATE - INTERVAL '15' MINUTE AND SYSDATE
    AND c.IDENTIFICATIONNUMBER IS NOT NULL 
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE,
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.ISSUEDATETIME,
    d.MRN


---------------------------------------------------------------------------

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRIM(d.MRN) IS NOT NULL
    AND d.DATEOFACCEPTANCE BETWEEN SYSDATE - INTERVAL '1' HOUR AND SYSDATE
    AND c.IDENTIFICATIONNUMBER IS NOT NULL
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE,
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.MRN

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.MRN, 
    LISTAGG(c.IDENTIFICATIONNUMBER, ', ' ON OVERFLOW TRUNCATE '...') 
        WITHIN GROUP (ORDER BY c.IDENTIFICATIONNUMBER) AS CONTAINERS 
FROM 
    EUCDM.EUCDECLARATION d 
JOIN 
    EUCDM.EUCCONTAINER c 
ON 
    d.DECLARATIONGUID = c.DECLARATIONGUID 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE) -- Filter for the current day
    AND TRIM(d.MRN) IS NOT NULL               -- Ensure MRN is not empty or only spaces
    AND c.IDENTIFICATIONNUMBER IS NOT NULL    -- Ensure container identification is present
GROUP BY 
    d.DECLARATIONID,
    d.DATEOFACCEPTANCE,
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    d.MRN

-- ------------------------------------------------------------------------ --
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE
FROM 
    EUCDM.EUCDECLARATION d 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE) 
    AND d.TYPEDECLARATIONSSW = 'EDMS_EXPORT'
    AND d.PROCEDURETYPESSW = 'B1'
    AND d.MESSAGESTATUS != 'DELETED'

UNION ALL

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE
FROM 
    EUCDM.EUCDECLARATION d 
WHERE
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND d.TYPEDECLARATIONSSW = 'EDMS_IMPORT'
    AND d.MESSAGESTATUS != 'DELETED'





-------------------------------
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE
FROM 
    EUCDM.EUCDECLARATION d 
WHERE 
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE) 
    AND d.TYPEDECLARATIONSSW = 'EDMS_EXPORT'
    AND d.PROCEDURETYPESSW = 'B1'
    AND d.MESSAGESTATUS != 'DELETED'

UNION ALL

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE, 
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE
FROM 
    EUCDM.EUCDECLARATION d 
WHERE
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND d.TYPEDECLARATIONSSW = 'EDMS_IMPORT'
    AND d.MESSAGESTATUS != 'DELETED'
---------------------------------------
SELECT 
    *
FROM 
    EUCDM.EUCDECLARATION d 
WHERE
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
-------------------------------
SELECT * FROM EUCDM.EUCHISTORY
FETCH FIRST 2 ROWS ONLY
-----------------------------
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE,
    TO_CHAR(h.HISTORYDATETIME, 'YYYY-MM-DD HH24:MI:SS') AS HISTORYDATETIME,
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE,
    h.MESSAGESTATUS
FROM 
    EUCDM.EUCDECLARATION d
JOIN 
    EUCDM.EUCHISTORY h
ON 
    d.DECLARATIONGUID = h.DECLARATIONGUID      
WHERE
    TRUNC(d.DATEOFACCEPTANCE) = TRUNC(SYSDATE)
    AND d.DECLARATIONID = 39830
    AND h.MESSAGESTATUS = "NEW"    
---------------------------
{
  "Table1": [
    {
      "HISTORYGUID": "/z+CloRCRNchgwjb+w7ddA==",
      "DECLARATIONGUID": "W4Hi9gY0QI+X+wjb+w7dag==",
      "MESSAGESTATUS": "COPIED",
      "COMMUNICATIONSTATUS": " ",
      "COMPUTERNAME": "RD2",
      "USERCODE": "ADMIN",
      "HISTORYDATETIME": "2023-12-12T13:35:47",
      "BATCHJOBID": 0,
      "DESCRIPTION": "Copy from PLDA Template ID :956110",
      "MAILBOX": " ",
      "MESSAGESHORTFILENAME": " ",
      "MESSAGEDIRECTION": " ",
      "INTERFACELOGRUNNUMBER": 0,
      "APPLICATIONVERSION": "504.1.006",
      "CUSTOMSREFERENCE": " ",
      "INTERFACEFILEGUID": null
    },
    {
      "HISTORYGUID": "X9zMhbGdQz+W1Qjb+w7diQ==",
      "DECLARATIONGUID": "+29VVCYKTY7SJQjb+w7dhA==",
      "MESSAGESTATUS": "COPIED",
      "COMMUNICATIONSTATUS": " ",
      "COMPUTERNAME": "RD2",
      "USERCODE": "ADMIN",
      "HISTORYDATETIME": "2023-12-12T13:35:47",
      "BATCHJOBID": 0,
      "DESCRIPTION": "Copy from PLDA Template ID :956749",
      "MAILBOX": " ",
      "MESSAGESHORTFILENAME": " ",
      "MESSAGEDIRECTION": " ",
      "INTERFACELOGRUNNUMBER": 0,
      "APPLICATIONVERSION": "504.1.006",
      "CUSTOMSREFERENCE": " ",
      "INTERFACEFILEGUID": null
    }
  ]
}
----------------------------------------------------------
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(h.HISTORYDATETIME, 'YYYY-MM-DD HH24:MI:SS') AS HISTORYDATETIME,
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE,
    h.MESSAGESTATUS
FROM 
    EUCDM.EUCDECLARATION d
JOIN 
    EUCDM.EUCHISTORY h
ON 
    d.DECLARATIONGUID = h.DECLARATIONGUID      
WHERE 
    d.TYPEDECLARATIONSSW = 'EDMS_EXPORT'
    AND d.PROCEDURETYPESSW = 'B1'
    AND d.MESSAGESTATUS != 'DELETED'
    AND h.HISTORYDATETIME >= SYSDATE - INTERVAL '1' HOUR 
    AND h.MESSAGESTATUS NOT IN ('COPIED', 'NEW', 'INTERFACE')
    AND d.CONSIGNEENAME IS NOT NULL AND d.CONSIGNEENAME <> ''
    AND d.CONSIGNEESTREETANDNUMBER IS NOT NULL AND d.CONSIGNEESTREETANDNUMBER <> ''
    AND d.CONSIGNEECOUNTRY IS NOT NULL AND d.CONSIGNEECOUNTRY <> ''
    AND d.CONSIGNEECITY IS NOT NULL AND d.CONSIGNEECITY <> ''
    AND d.CONSIGNEEPOSTCODE IS NOT NULL AND d.CONSIGNEEPOSTCODE <> ''

UNION ALL

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(h.HISTORYDATETIME, 'YYYY-MM-DD HH24:MI:SS') AS HISTORYDATETIME,
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE,
    h.MESSAGESTATUS
FROM 
    EUCDM.EUCDECLARATION d
JOIN 
    EUCDM.EUCHISTORY h
ON 
    d.DECLARATIONGUID = h.DECLARATIONGUID      
WHERE 
    d.TYPEDECLARATIONSSW = 'EDMS_IMPORT'
    AND d.MESSAGESTATUS != 'DELETED'
    AND h.HISTORYDATETIME >= SYSDATE - INTERVAL '15' MINUTE
    AND h.MESSAGESTATUS = 'MODIFIED'
    AND d.CONSIGNEENAME IS NOT NULL AND d.CONSIGNEENAME <> ''
    AND d.CONSIGNEESTREETANDNUMBER IS NOT NULL AND d.CONSIGNEESTREETANDNUMBER <> ''
    AND d.CONSIGNEECOUNTRY IS NOT NULL AND d.CONSIGNEECOUNTRY <> ''
    AND d.CONSIGNEECITY IS NOT NULL AND d.CONSIGNEECITY <> ''
    AND d.CONSIGNEEPOSTCODE IS NOT NULL AND d.CONSIGNEEPOSTCODE <> ''
------------------------------------------------------------------------------------
WITH LatestHistory AS (
    SELECT 
        h.DECLARATIONGUID,
        h.MESSAGESTATUS AS HISTORYMESSAGESTATUS,
        TO_CHAR(h.HISTORYDATETIME, 'YYYY-MM-DD HH24:MI:SS') AS HISTORYDATETIME,
        ROW_NUMBER() OVER (PARTITION BY h.DECLARATIONGUID ORDER BY h.HISTORYDATETIME DESC) AS rn
    FROM EUCDM.EUCHISTORY h
    WHERE h.HISTORYDATETIME >= SYSDATE - INTERVAL '15' MINUTE
    AND h.MESSAGESTATUS = 'MODIFIED'
)
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    lh.HISTORYDATETIME,
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE,
    lh.HISTORYMESSAGESTATUS 
FROM EUCDM.EUCDECLARATION d
JOIN LatestHistory lh 
ON d.DECLARATIONGUID = lh.DECLARATIONGUID
WHERE 
    d.TYPEDECLARATIONSSW = 'EDMS_EXPORT'
    AND d.PROCEDURETYPESSW = 'B1'
    AND d.MESSAGESTATUS != 'DELETED'
    AND lh.rn = 1
    AND d.CONSIGNEENAME <> ' '
    AND d.CONSIGNEESTREETANDNUMBER <> ' '
    AND d.CONSIGNEECOUNTRY <> ' '
    AND d.CONSIGNEECITY <> ' '
    AND d.CONSIGNEEPOSTCODE <> ' '

UNION ALL

WITH LatestHistory AS (
    SELECT 
        h.DECLARATIONGUID,
        h.MESSAGESTATUS AS HISTORYMESSAGESTATUS,
        TO_CHAR(h.HISTORYDATETIME, 'YYYY-MM-DD HH24:MI:SS') AS HISTORYDATETIME,
        ROW_NUMBER() OVER (PARTITION BY h.DECLARATIONGUID ORDER BY h.HISTORYDATETIME DESC) AS rn
    FROM EUCDM.EUCHISTORY h
    WHERE h.HISTORYDATETIME >= SYSDATE - INTERVAL '15' MINUTE
    AND h.MESSAGESTATUS = 'MODIFIED'
)

SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    lh.HISTORYDATETIME,
    d.CONSIGNEENAME,
    d.CONSIGNEESTREETANDNUMBER,
    d.CONSIGNEECOUNTRY,
    d.CONSIGNEECITY,
    d.CONSIGNEEPOSTCODE,
    lh.HISTORYMESSAGESTATUS 
FROM EUCDM.EUCDECLARATION d
JOIN LatestHistory lh 
ON d.DECLARATIONGUID = lh.DECLARATIONGUID
WHERE 
    d.TYPEDECLARATIONSSW = 'EDMS_IMPORT'
    AND d.MESSAGESTATUS = 'DELETED'
    AND lh.rn = 1
    AND d.CONSIGNEENAME <> ' '
    AND d.CONSIGNEESTREETANDNUMBER <> ' '
    AND d.CONSIGNEECOUNTRY <> ' '
    AND d.CONSIGNEECITY <> ' '
    AND d.CONSIGNEEPOSTCODE <> ' '



WITH FilteredDeclarations AS (
    SELECT DISTINCT d.DECLARATIONGUID
    FROM EUCDM.EUCDECLARATION d
    JOIN EUCDM.EUCHISTORY h 
    ON d.DECLARATIONGUID = h.DECLARATIONGUID
    WHERE h.MESSAGESTATUS = 'DMSCLE'
    AND h.HISTORYDATETIME >= SYSDATE - INTERVAL '1' HOUR
)
SELECT 
    d.DECLARATIONID,
    d.MESSAGESTATUS AS DECLARATION_STATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    h.HISTORYDATETIME,
    h.MESSAGESTATUS AS HISTORY_STATUS
FROM EUCDM.EUCHISTORY h
JOIN EUCDM.EUCDECLARATION d ON d.DECLARATIONGUID = h.DECLARATIONGUID
JOIN FilteredDeclarations fd ON h.DECLARATIONGUID = fd.DECLARATIONGUID
ORDER BY d.DECLARATIONID, h.HISTORYDATETIME

SELECT 
*
FROM EUCDM.EUCHISTORY h
JOIN EUCDM.EUCDECLARATION d ON d.DECLARATIONGUID = h.DECLARATIONGUID
WHERE d.DECLARATIONID = 39830
FETCH FIRST 2 ROWS ONLY
-----------------------------------------------------------
SELECT 
    d.DECLARATIONID, 
    d.MESSAGESTATUS,
    d.ACTIVECOMPANY,
    d.USERCREATE,
    d.TYPEDECLARATIONSSW,
    TO_CHAR(d.DATEOFACCEPTANCE, 'YYYY-MM-DD HH24:MI:SS') AS DATEOFACCEPTANCE
FROM 
    EUCDM.EUCDECLARATION d 
WHERE 
    d.PROCEDURETYPESSW = 'H2'
    AND (d.WAREHOUSEIDENTIFIER = 'BECWPG00150' OR  d.WAREHOUSEIDENTIFIER = 'BECWPA00238')
    AND d.MESSAGESTATUS = 'DMSCLE'